CREATE TABLE captacion_sociodemograficos (
	"NPAIS" INTEGER NOT NULL, 
	"NCANAL" INTEGER NOT NULL, 
	"NSUCURSAL" INTEGER NOT NULL, 
	"NFOLIO" INTEGER NOT NULL, 
	"CAP_VCP" VARCHAR(5) NOT NULL, 
	"CAP_VESTADO" VARCHAR(20), 
	"CAP_VDELMUNIC" VARCHAR(40), 
	"CAP_VGENERO" VARCHAR(4), 
	"CAP_EDAD_ANIOS" INTEGER NOT NULL, 
	"CAP_VEDOCIVIL" VARCHAR(20)
);
