---
title: "Prueba de modelo"
author: "Metronhomo"
date: "Enero 2016"
output: html_document
---

Para el problema de predecir qué cliente va a tomar un crédito cuando se le ofrezca se calcularon cuatro modelos: Bosques aleatorios, gradient boosting, máquina de soporte vectorial y regresión logística. Los resultados en la primera etapa parecían ser muy satisfactorios, sin embargo, se debe probar con nuevos clientes para corroborar que el modelo prediga bien con una nueva muestra independiente de clientes. En este documento se presentan los resultados de esta nueva prueba.

Los modelos originales se entrenaron con 74,384 personas de las cuales 18,746 tenían crédito en los años 2014 y 2015, y el resto eran personas de captación. Para esta prueba se utiliza la información transaccional de 5,608,900 personas que tienen movimientos en septiembre de 2015. Se revisó que estas personas no estuvieran en el catálogo de clientes de crédito y además se descartaron a los datos atípicos que tenían un gran número de transacciones. Después se calcularon las variables que se utilizan en los modelos, tomando un año hacia atrás a partir de su última transacción. El objetivo es comprobar que los clientes que el modelo diga que se van a convertir a crédito, en realidad lo han hecho en el tiempo posterior a septiembre de 2015.

Los resultados de los cuatro modelos para los nuevos datos se pueden ver a continuación:

#Random Forest

#SVM

#Gradient Boosting

#Regresión logística


